# Check /usr/lib/firewalld/services 
# for overview of services
- name: Ensuring firewall ports are open
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - https
    - http
 #notify:
 # - Reloading service firewalld

# Optional handler
- name: Reloading service firewalld
  systemd:
    name: firewalld
    state: reloaded
