- name: Editing configuration file
  lineinfile:                         
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.search }}"  
    line: "{{ item.replace }}"
  with_items:
    - { search: '^#network.host:', replace: 'network.host: 0.0.0.0' }
    - { search: '^#discovery.seed_hosts', replace: 'discovery.seed_hosts: ["host1", "host2"]' }
